

###  ATTACHING OUR TEMPLATES


## AS WE HAD CREATED A TEMPLATE DIRECTORY IN CRM APP, WE WILL DO THE SAME WITH JOURNAL. AND WITHIN THAT TEMPLATE WE WIL CREATE A FOLDER
## JOURNAL AND WE WIL STORE OUR TEMPLATES THERE

## NOW AS WE HAVE FOUR VIEWS, WE WILL CREATE FOUR TEMPLATES
## AND WE WILL JUST HAVE SOME CONTENT IN THEM JUST FOR TESTING PURPOSES




