
###########  PROTECTING OUR VIEWS

### WE HAVE READ ABOUT THIS WHAT IS THIS AND WHY WE DO THIS, WE JUST USE A DECORATOR AND ATTACH IT TO ONE OF THE VIEWS, WHICH CONTAINS PERSONAL
### INFO AND WE DONT WANT ANYONE TO ACCESS IT WITHOUT LOGGIN IN DIRECTKY FROM URL

##############  VIEWS.PY FILE

@login_required(login_url='my-login')
def dashboard(request):

    return render(request, 'journal/dashboard.html')

## HERE ABOVE WE CAN SEE, WE HAVE PROTECT OUR DASHBOARD FROM DIRECT ACCESS AND NOW IF WE TRY TO DO SO, WE WILL BE REDIRECTED TO LOGIN FORM